routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth routes.
Route::resource('/authenticate','Auth\Logincontroller')->middleware(['back','path']);
Route::post('/login-verify','Auth\Logincontroller@login')->name('login')->middleware(['back','path']);
Route::resource('/home','Home\Homecontroller');


//Agent  routes
Route::group(['middleware'=>['web','access','agent','back']],function(){
    Route::resource('/agent','Agent\Agentcontroller');
    Route::resource('/property','Property\Basicinfo');
    Route::get('/featured-images/{id}','Property\FeatureImages@index')->name('featured');
    Route::post('/upload-featured','Property\FeatureImages@imageUpload');
    Route::get('/featured-delete/{id}','Property\FeatureImages@delete')->name('delete');
    Route::get('/gallery-images/{id}','Property\GalleryImages@index')->name('gallery');
    Route::post('/upload-gallery','Property\GalleryImages@imageUpload');
    Route::get('/gallery-delete/{id}','Property\GalleryImages@delete')->name('gallerydelete');
    Route::get('/near-place/{id}','Property\Nearplace@index')->name('place');
    Route::post('/add-place','Property\Nearplace@addPlace')->name('placeAdd');
    Route::get('/place-delete/{id}','Property\Nearplace@delete')->name('placedelete');
});

//Logout 
Route::group(['middleware'=>['web','access','back']],function(){
    Route::get('/logout','Auth\Logincontroller@logout')->name('logout');
});

//Customer routes
Route::group(['middleware'=>['web','access','customer','back']],function(){
    Route::resource('/customer','Customer\Customercontroller');
});

app/Http/Controllers/Agent/Agentcontroller.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\Profile;
use App\Message;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Mail;


class Agentcontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data=Message::where('enquiredUser',Session::get('userid'))->paginate(10);
        return view('agent.dashboard',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data=$request->all();
        if(isset($data['mail']))
        {
            $request->validate([
                'subject'=>'required',
                'content'=>'required'
            ]);
            $email=$data['email'];
            $maildata=array("content"=>$data['content']);
            $subject=$data['subject'];
           Mail::send('mail',$maildata,function($message) use ($email,$subject)
            {
                $message->to($email)->subject("$subject");
                $message->from("info@dealswid.com","Realstate");
            });
            return redirect()->back()->with('success','Email has been sent successfully');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $id=base64_decode($id);
        $data=Message::where('messageId',$id)->first();
        return view('agent.view-enquiry',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data=Profile::getProfileDetails($id);
        return view('agent.profile',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data=$request->all();
        
        $updated_record=Profile::updateUserData($data,$id);
        if($updated_record)
        {
            return redirect()->back()->with('success','You have updated profile successfully');

        }
        return redirect()->back()->with('warning','Profile update failed');
       

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/agent/add-property.blade.php
@extends('layout.layout')

@section('title','Add Property')

@section('content')

    <b><br>Add your property here.
        <hr>
        @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
        @elseif (Session::get('warning'))
        <div class="alert alert-danger alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('warning')}}
        </div>
        @endif

        <form action="{{route('property.store')}}" method='post' id="propertyForm">
            @csrf
         <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Property Title</label>
                <input type="text" name="title" id="title" class="form-control" placeholder="Enter property title" value="{{old('title')}}">
                <span style='color:red'>
                    @error('title'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input type="text" name="price" id="price" class="form-control" placeholder="Enter property price" value="{{old('price')}}">
                <span style='color:red'>
                    @error('price'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Floor Area(In SQFT)</label>
                <input type="text" name="area" id="area" class="form-control" placeholder="Enter floor area" value="{{old('area')}}">
                <span style='color:red'>
                    @error('area'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">No of Bedrooms</label>
                <input type="number" name="bedroom" id="bedroom" class="form-control" placeholder="Enter no of bedrooms" min="1" step="1" value="{{old('bedroom')}}">
                <span style='color:red'>
                    @error('bedroom'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
           <div class="form-group">
                <label for="exampleInputEmail1">No of Bathrooms</label>
                <input type="number" name="bathroom" id="bathroom" class="form-control" placeholder="Enter no of bedrooms" min="1" step="1" value="{{old('bathroom')}}">
                <span style='color:red'>
                    @error('bathroom'){{$message}}@enderror
                </span>
            </div>
            
            </div>
        <div class="col-md-6">
        <div class="form-group">
                <label for="exampleInputEmail1">City</label>
                <select name="city" id="city" class="form-control">
                <option value="">--Select City--</option>
                @foreach($data as $city)
                <option value="{{$city->cityId}}">{{$city->cityName}}</option>
                @endforeach
                </select>
                  <span style='color:red'>
                    @error('city'){{$message}} @enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Address</label>
                <input type="text" name="address" id="address" class="form-control" placeholder="Enter property address" value="{{old('address')}}">
                <span style='color:red'>
                    @error('address'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Description</label>
                <textarea class='form-control' name="description" id="description">{{old('description')}}</textarea>
                <span style='color:red'>
                    @error('description'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
            <button type="submit" class="btn btn-success" name='addProperty' value='yes'>Add Property</button>
        </form>
       

@stop

resources/views/agent/dashboard.blade.php
@extends('layout.layout')

@section('title','Agent Dashboard')

@section('content')
@if (Session::get('success'))
<div class="alert alert-success alert-dismissible">
    <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    {{Session::get('success')}}
</div>
@elseif (Session::get('warning'))
<div class="alert alert-danger alert-dismissible">
    <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    {{Session::get('warning')}}
</div>
@endif
<br>
<h4>Enquaries:</h4>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"> Name</th>
      <th scope="col">Email</th>
      <th scope="col">Contact</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>@php $n=1; @endphp
  @foreach($data as $message)
    <tr>
      <th scope="row">{{$n++}}</th>
      <td>{{$message->name}}</td>
      <td>{{$message->email}}</td>
      <td>{{$message->contact}}</td>
      
      <td> 
        <a href="{{route('agent.show',base64_encode($message->messageId))}}"><i class="fa fa-eye"></i></a>
       
      </td>
    </tr>
    @endforeach
    
  </tbody>
</table>
{{$data->links()}}
@stop

resources/views/agent/edit-property.blade.php
@extends('layout.layout')

@section('title','Edit Property')

@section('content')

    <b><br>Edit your property.
        <hr>
        @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
        @elseif (Session::get('warning'))
        <div class="alert alert-danger alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('warning')}}
        </div>
        @endif

        <form action="{{route('property.update',base64_encode($data->propertyId))}}" method='post' id="propertyForm">
        @method('PUT')
            @csrf
         <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Property Title</label>
                <input type="text" name="title" id="title" class="form-control" placeholder="Enter property title" value="{{$data->title}}">
                <span style='color:red'>
                    @error('title'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input type="text" name="price" id="price" class="form-control" placeholder="Enter property price" value="{{$data->price}}">
                <span style='color:red'>
                    @error('price'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Floor Area(In SQFT)</label>
                <input type="text" name="area" id="area" class="form-control" placeholder="Enter floor area" value="{{$data->area}}">
                <span style='color:red'>
                    @error('area'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">No of Bedrooms</label>
                <input type="number" name="bedroom" id="bedroom" class="form-control" placeholder="Enter no of bedrooms" min="1" step="1" value="{{$data->bedroom}}">
                <span style='color:red'>
                    @error('bedroom'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
           <div class="form-group">
                <label for="exampleInputEmail1">No of Bathrooms</label>
                <input type="number" name="bathroom" id="bathroom" class="form-control" placeholder="Enter no of bedrooms" min="1" step="1" value="{{$data->bathroom}}">
                <span style='color:red'>
                    @error('bathroom'){{$message}}@enderror
                </span>
            </div>
            
            </div>
        <div class="col-md-6">
        <div class="form-group">
                <label for="exampleInputEmail1">City</label>
                <select name="city" id="city" class="form-control">
                <option value="">--Select City--</option>
                @foreach($city as $cities)
                <option value="{{$cities->cityId}}" {{$cities->cityId==$data->city?'selected':''}}>{{$cities->cityName}}</option>
                @endforeach
                </select>
                  <span style='color:red'>
                    @error('city'){{$message}} @enderror
                </span>
            </div>
        </div>
        </div>
        <div class="row">
           <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Address</label>
                <input type="text" name="address" id="address" class="form-control" placeholder="Enter property address" value="{{$data->address}}">
                <span style='color:red'>
                    @error('address'){{$message}} @enderror
                </span>
            </div>
            </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Description</label>
                <textarea class='form-control' name="description" id="description">{{$data->description}}</textarea>
                <span style='color:red'>
                    @error('description'){{$message}}@enderror
                </span>
            </div>
        </div>
        </div>
            <button type="submit" class="btn btn-success" name='updateProperty' value='yes'>Update Property</button>
        </form>
       

@stop

resources/views/agent/profile.blade.php
@extends('layout.layout')

@section('title','Agent Profile')

@section('content')
<div class='col-sm-6'>
    <b><br>Your profile
        <hr>
        @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
        @elseif (Session::get('warning'))
        <div class="alert alert-danger alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('warning')}}
        </div>
        @endif


        <form action="{{route('agent.update',base64_encode($data->userId))}}" method='post' id="registerForm" enctype="multipart/form-data">
        @method('PUT')
            @csrf
            <img class="profile_img" src='{{asset("storage/uploads/$data->userImage")}}' alt="" />
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Enter your email" value="{{$data->userEmail}}" readonly>
                <span style='color:red'>
                    @error('email'){{$message}} @enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="name" name="name" id="name" class="form-control" placeholder="Enter your email" value="{{$data->userName}}">
                <span style='color:red'>
                    @error('email'){{$message}} @enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Enter your password" value="{{base64_decode($data->password)}}">
                <span style='color:red'>
                    @error('password'){{$message}}@enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Profile Image</label>
                <input type="file" name="file" id="file" class="form-control" accept="image/x-png,image/jpg,image/jpeg">
                <span style='color:red'>
                    @error('file'){{$message}}@enderror
                </span>
            </div>
            <button type="submit" class="btn btn-success" name='isUpdate' value='yes'>Update</button>
        </form>
       
</div>


@stop

resources/views/agent/property-listing.blade.php
@extends('layout.layout')

@section('title','Property Listing')

@section('content')

  
      
        @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
        @elseif (Session::get('warning'))
        <div class="alert alert-danger alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('warning')}}
        </div>
        @endif
        <hr>
        <a href="{{route('property.create')}}">Add Properties</a><br><br>
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Property Name</th>
      <th scope="col">Price</th>
      <th scope="col">Featured Images</th>
      <th scope="col">Gallery Images</th>
      <th scope="col">Neary By Places</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>@php $n=1; @endphp
  @foreach($data as $proeprty)
    <tr>
      <th scope="row">{{$n++}}</th>
      <td>{{$proeprty->title}}</td>
      <td>{{$proeprty->price}}</td>
      <td><a href="{{route('featured',base64_encode($proeprty->propertyId))}}">Upload</a></td>
      <td><a href="{{route('gallery',base64_encode($proeprty->propertyId))}}">Upload</a></td>
      <td><a href="{{route('place',base64_encode($proeprty->propertyId))}}">Add</a></td>
      <td> 
        <a href="{{route('property.show',base64_encode($proeprty->propertyId))}}"> <i class="fa fa-eye"></i></a>
        <a href="{{route('property.edit',base64_encode($proeprty->propertyId))}}"><i class="fa fa-edit"></i></a>
        <form action="{{route('property.destroy',base64_encode($proeprty->propertyId))}}" method="post">
        @csrf
        @method('DELETE')
        <button type="submit" class="text-danger" title="Delete">
        <i class="fa fa-trash"></i></button>
        </form>
      </td>
    </tr>
    @endforeach
    
  </tbody>
</table>
{{$data->links()}}
@stop

resources/views/agent/view-enquiry.blade.php
@extends('layout.layout')

@section('title','Enquiry View')

@section('content')
<style>
* {
  box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

/* Style the container/contact section */
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 10px;
}

/* Create two columns that float next to eachother */
.column {
  float: left;
  width: 50%;
  margin-top: 6px;
  padding: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}

</style>
<div class="container">
  <div style="text-align:center">
    <h2>Enquiry Details</h2>
    
  </div>
  <div class="row">
    <div class="column">
      <table  class="table">
      <tr><td><b>Person Name : </b></td><td>{{$data->name}}</td></tr>
      <tr><td><b>Email : </b></td><td>{{$data->email}}</td></tr>
      <tr><td><b>Contact : </b></td><td>{{$data->contact}}</td></tr>
      <tr><td><b>Message : </b></td><td>{{$data->message}}</td></tr>
      </table>
    </div>
    <div class="column">
    @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
    @endif
      <form action="{{route('agent.store')}}" method="post" >
      @csrf
        <label for="name">Email</label>
        <input type="text" id="email" name="email" value="{{$data->email}}" readonly>
        
        <br>
        <label for="email">Subject</label>
        <input type="text" id="subject" name="subject" >
        @error('subject')<span style="color:red">{{$message}}</span>@enderror
        <br>
        <label for="subject">Email Content</label>
        <textarea id="content" name="content" placeholder="Write something.." style="height:170px"></textarea>
        @error('content')<span style="color:red">{{$message}}</span>@enderror<br>
        <input type="submit" value="Submit" name="mail" value="yes">
      </form>
    </div>
  </div>
</div>
@stop

resources/views/agent/view-property.blade.php
@extends('layout.layout')

@section('title','Property Detail')

@section('content')
<style>
* {
  box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

/* Style the container/contact section */
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 10px;
}

/* Create two columns that float next to eachother */
.column {
  float: left;
  width: 50%;
  margin-top: 6px;
  padding: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}

</style>
<div class="container">
  <div style="text-align:center">
    <h2>Property Details</h2>
    
  </div>
  <div class="row">
    <div class="column">
      <table  class="table">
      <tr><td><b>Property Title : </b></td><td>{{$data->title}}</td></tr>
      <tr><td><b>Floor Area(Sqft) : </b></td><td>{{$data->area}}</td></tr>
      <tr><td><b>Price : </b></td><td>{{$data->price}}</td></tr>
      <tr><td><b>Bedroom : </b></td><td>{{$data->bedroom}}</td></tr>
      <tr><td><b>Bathroom : </b></td><td>{{$data->bathroom}}</td></tr>
      <tr><td><b>Address : </b></td><td>{{$data->address}}</td></tr>
      <tr><td><b>City: </b></td><td>{{getCityName($data->city)}}</td></tr>
      <tr><td><b>Address : </b></td><td>{{$data->address}}</td></tr>
      <tr><td><b>Description : </b></td><td>{{$data->description}}</td></tr>
      </table>
    </div>
    <div class="column">
   
    </div>
  </div>
</div>
@stop