routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth routes.
Route::resource('/authenticate','Auth\Logincontroller')->middleware(['back','path']);
Route::post('/login-verify','Auth\Logincontroller@login')->name('login')->middleware(['back','path']);
Route::resource('/home','Home\Homecontroller');


//Agent  routes
Route::group(['middleware'=>['web','access','agent','back']],function(){
    Route::resource('/agent','Agent\Agentcontroller');
    Route::resource('/property','Property\Basicinfo');
    Route::get('/featured-images/{id}','Property\FeatureImages@index')->name('featured');
    Route::post('/upload-featured','Property\FeatureImages@imageUpload');
    Route::get('/featured-delete/{id}','Property\FeatureImages@delete')->name('delete');
    Route::get('/gallery-images/{id}','Property\GalleryImages@index')->name('gallery');
    Route::post('/upload-gallery','Property\GalleryImages@imageUpload');
    Route::get('/gallery-delete/{id}','Property\GalleryImages@delete')->name('gallerydelete');
    Route::get('/near-place/{id}','Property\Nearplace@index')->name('place');
    Route::post('/add-place','Property\Nearplace@addPlace')->name('placeAdd');
    Route::get('/place-delete/{id}','Property\Nearplace@delete')->name('placedelete');
});

//Logout 
Route::group(['middleware'=>['web','access','back']],function(){
    Route::get('/logout','Auth\Logincontroller@logout')->name('logout');
});

//Customer routes
Route::group(['middleware'=>['web','access','customer','back']],function(){
    Route::resource('/customer','Customer\Customercontroller');
});

resources/views/layout/layout.blade.php
<html>

<head>
  <title>Page Name- @yield('title')</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/yourcode.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{asset('css/filter.css')}}">


</head>

<body>
  <!--section inside the div or divv inside the section both are feasible-->
  @section('header')
  <div class="header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Realstate</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{route('home.index')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          @if(Session::get('role')==1)
          <li class="nav-item">
            <a class="nav-link" href="{{route('property.index')}}">Your Properties</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('agent.index')}}" tabindex="-1">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('agent.edit',base64_encode(Session::get('userid')))}}" tabindex="-1">Profile</a>
          </li>
          @elseif(Session::get('role')==2)
          <li class="nav-item">
            <a class="nav-link" href="{{route('customer.index')}}" tabindex="-1">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('customer.edit',base64_encode(Session::get('userid')))}}" tabindex="-1">Profile</a>
          </li>

          @endif
          <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->

        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
        <!-- <button class="btn btn-outline-success my-2 my-sm-0">-->
        @if(!Session::get('userid'))
        <a href="{{route('authenticate.index')}}" class="btn btn-success my-2 my-sm-0">Login</a>
        @else
        <a class="nav-link">Welcome! {{Session::get('username')}}</a>
        <a href="{{route('logout')}}" class="btn btn-success my-2 my-sm-0">Logout</a>
        @endif
        <!-- </button> -->
        <!-- </form> -->
      </div>
    </nav>
  </div>
  @show
  <div class="container">
    @yield('content')
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{asset('js/main.js')}}"></script>
    <script src="{{asset('js/validate.js')}}"></script>
  </div>

</body>

</html>