routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth routes.
Route::resource('/authenticate','Auth\Logincontroller')->middleware(['back','path']);
Route::post('/login-verify','Auth\Logincontroller@login')->name('login')->middleware(['back','path']);
Route::resource('/home','Home\Homecontroller');


//Agent  routes
Route::group(['middleware'=>['web','access','agent','back']],function(){
    Route::resource('/agent','Agent\Agentcontroller');
    Route::resource('/property','Property\Basicinfo');
    Route::get('/featured-images/{id}','Property\FeatureImages@index')->name('featured');
    Route::post('/upload-featured','Property\FeatureImages@imageUpload');
    Route::get('/featured-delete/{id}','Property\FeatureImages@delete')->name('delete');
    Route::get('/gallery-images/{id}','Property\GalleryImages@index')->name('gallery');
    Route::post('/upload-gallery','Property\GalleryImages@imageUpload');
    Route::get('/gallery-delete/{id}','Property\GalleryImages@delete')->name('gallerydelete');
    Route::get('/near-place/{id}','Property\Nearplace@index')->name('place');
    Route::post('/add-place','Property\Nearplace@addPlace')->name('placeAdd');
    Route::get('/place-delete/{id}','Property\Nearplace@delete')->name('placedelete');
});

//Logout 
Route::group(['middleware'=>['web','access','back']],function(){
    Route::get('/logout','Auth\Logincontroller@logout')->name('logout');
});

//Customer routes
Route::group(['middleware'=>['web','access','customer','back']],function(){
    Route::resource('/customer','Customer\Customercontroller');
});

app/Http/Controllers/Customer/Customercontroller.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services\Profile;


class Customercontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('customer.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data=Profile::getProfileDetails($id);
        return view('customer.profile',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data=$request->all();
        
        $updated_record=Profile::updateUserData($data,$id);
        if($updated_record)
        {
            return redirect()->back()->with('success','You have updated profile successfully');

        }
        return redirect()->back()->with('warning','Profile update failed');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/dashboard.blade.php
@extends('layout.layout')

@section('title','Customer Dashboard')

@section('content')
@if (Session::get('success'))
<div class="alert alert-success alert-dismissible">
    <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    {{Session::get('success')}}
</div>
@elseif (Session::get('warning'))
<div class="alert alert-danger alert-dismissible">
    <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

    {{Session::get('warning')}}
</div>
@endif

@stop

resources/views/customer/profile.blade.php
@extends('layout.layout')

@section('title','Customer Profile')

@section('content')
<div class='col-sm-6'>
    <b><br>Your profile
        <hr>
        @if (Session::get('success'))
        <div class="alert alert-success alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('success')}}
        </div>
        @elseif (Session::get('warning'))
        <div class="alert alert-danger alert-dismissible">
            <button style="color:#fff" type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>

            {{Session::get('warning')}}
        </div>
        @endif

        <form action="{{route('customer.update',base64_encode($data->userId))}}" method='post' id="registerForm" enctype="multipart/form-data">
        @method('PUT')    @csrf
        <img class="profile_img" src='{{($data->userImage=="")?asset("default-icon.png"):asset("storage/uploads/$data->userImage")}}' alt="" />
           
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" name="email" id="email" class="form-control" placeholder="Enter your email" value="{{$data->userEmail}}" readonly>
                <span style='color:red'>
                    @error('email'){{$message}} @enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="name" name="name" id="name" class="form-control" placeholder="Enter your email" value="{{$data->userName}}">
                <span style='color:red'>
                    @error('email'){{$message}} @enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Password</label>
                <input type="password" name="password" idd="password" class="form-control" placeholder="Enter your password" value="{{base64_decode($data->password)}}">
                <span style='color:red'>
                    @error('password'){{$message}}@enderror
                </span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Profile Image</label>
                <input type="file" name="file" id="file" class="form-control" accept="image/x-png,image/jpg,image/jpeg">
                <span style='color:red'>
                    @error('file'){{$message}}@enderror
                </span>
            </div>
            <button type="submit" class="btn btn-success" name='isUpdate' value='yes'>Update</button>
        </form>
       
</div>


@stop